name: cloob
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - absl-py
  - blas
  - blas-devel
  - blinker
  - brotli
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cachetools
  - cffi
  - cryptography
  - cudatoolkit=11.3.1
  - cycler
  - dataclasses
  - expat
  - ffmpeg
  - fontconfig
  - fonttools
  - freetype
  - ftfy
  - glib
  - google-auth
  - google-auth-oauthlib
  - grpcio
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - importlib-metadata
  - jbig
  - jpeg
  - kiwisolver
  - lcms2
  - lerc
  - libblas
  - libcblas
  - libdeflate
  - libffi
  - libiconv
  - liblapack
  - liblapacke
  - libpng
  - libprotobuf
  - libtiff
  - libuv
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - llvm-openmp
  - lz4-c
  - markdown
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-devel
  - mkl-include
  - munkres
  - numpy=1.22.1
  - oauthlib
  - olefile
  - openjpeg
  - openssl
  - pandas
  - pcre
  - pillow
  - pip
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pyjwt
  - pyopenssl
  - pyqt
  - pysocks
  - python=3.9.7
  - python-dateutil
  - python_abi
  - pytorch=1.10.2
  - pytorch-mutex
  - pytz
  - qt
  - regex
  - requests
  - requests-oauthlib
  - rsa
  - sip
  - six
  - sqlite
  - tbb
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - tk
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - werkzeug
  - wheel
  - xz
  - zipp
  - zlib
  - zstd
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - argparse==1.4.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - black==22.1.0
    - bleach==4.1.0
    - braceexpand==0.1.7
    - certifi==2021.10.8
    - charset-normalizer==2.0.11
    - click==8.0.3
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - entrypoints==0.3
    - executing==0.8.2
    - gitdb==4.0.9
    - gitpython==3.1.26
    - ipykernel==6.8.0
    - ipython==8.0.1
    - ipython-genutils==0.2.0
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mypy-extensions==0.4.3
    - nbclient==0.5.10
    - nbconvert==6.4.1
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - notebook==6.4.8
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.4.1
    - prometheus-client==0.13.1
    - promise==2.3
    - prompt-toolkit==3.0.26
    - protobuf==3.19.4
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pygments==2.11.2
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - send2trash==1.8.0
    - sentry-sdk==1.5.4
    - setuptools==59.5.0
    - shortuuid==1.0.8
    - smmap==5.0.0
    - stack-data==0.1.4
    - termcolor==1.1.0
    - terminado==0.13.1
    - testpath==0.5.0
    - threadpoolctl==3.1.0
    - tomli==2.0.0
    - traitlets==5.1.1
    - wandb==0.12.10
    - webencodings==0.5.1
    - yaspin==2.1.0
    - git+https://github.com/ml-jku/hopfield-layers
    - git+https://github.com/tmbdev/webdataset.git
